/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
/* Header for class com_example_sm4byc_SM4byCUtils */

#ifndef _Included_com_example_sm4byc_SM4byCUtils
#define _Included_com_example_sm4byc_SM4byCUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_sm4byc_SM4byCUtils
 * Method:    encrypt_by_SM4CBC
 * Signature: ([B[B)Ljava/lang/String;
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_sm4byc_SM4byCUtils_encrypt_1by_1SM4CBC
  (JNIEnv *, jobject, jbyteArray, jbyteArray,jbyteArray,jint);

/*
 * Class:     com_example_sm4byc_SM4byCUtils
 * Method:    encrypt_by_SM4ECB
 * Signature: ([B[B)Ljava/lang/String;
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_sm4byc_SM4byCUtils_encrypt_1by_1SM4ECB
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_example_sm4byc_SM4byCUtils
 * Method:    decrypt_by_SM4CBC
 * Signature: ([B[B)Ljava/lang/String;
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_sm4byc_SM4byCUtils_decrypt_1by_1SM4CBC
  (JNIEnv *, jobject, jbyteArray,jbyteArray, jbyteArray);

/*
 * Class:     com_example_sm4byc_SM4byCUtils
 * Method:    decrypt_by_SM4ECB
 * Signature: ([B[B)Ljava/lang/String;
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_sm4byc_SM4byCUtils_decrypt_1by_1SM4ECB
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
